### ISSUE TITLE
Squash Git history into a single commit

### ISSUE THREAD

**Issue by emmaffiondavies** [Stack-in-a-box/sonic-the-hedgehog-speedrunners-edition#1]
# Overview

This codebase will eventually become distinct-enough from the original disassembly repository that the original history will be largely irrelevant. In addition to this, this fork is never intended to be merged back into the original repo so it's fine to squash history. Doing so will help keep the codebase tidy going forward so that the focus remains on the custom stuff that's being added. It should also reduce the total size of the repository to speed-up cloning.

The `s1disasm` history is only 207 commits deep (presumably the rest of the history was left behind when Sonic Retro migrated from SVN back in 2010) so the rebase shouldn't take an impractically long amount of time to complete. Squashing in chunks from the latest to the oldest commits _might_ be more efficient compared to doing it in chunks from the oldest to newest as Git may compute new diffs for each of the commits after the chunk even though those commits after the squashed ones haven't changed in their own right; I'm not positive about this but the worst case is that it takes the same amount of time so may as well give it a shot...

# Tasks

- [x] Delete [all old branches](https://www.github.com/Stack-in-a-box/sonic-the-hedgehog-speedrunners-edition/branches/all) except `master`.
- [x] Squash all commits down to a single one.
- [x] Wipe the readme in the root so it just contains the project name.

# Resources

Use this Stack Overflow answer as reference on how to perform the history squashing:
https://stackoverflow.com/questions/1657017/how-to-squash-all-git-commits-into-one/9254257#9254257
