### ISSUE TITLE
Work-out how to build the source and document the process

### ISSUE THREAD

**Issue by emmaffiondavies** [Stack-in-a-box/sonic-the-hedgehog-speedrunners-edition#2]
# Overview

It's not particularly obvious from the base repository's readme how to go about building the source into a runnable binary. Track-down a way to do so and then test the resulting ROM in an emulator to make sure it plays fine with no crashes, missing assets, etc. When this process has been established, document it on _this_ repo's readme (including how to run it in an emulator) so it's easier for other people to contribute in future.

There's a file called `sonic1built.bin` which I'd assume is a precompiled binary of Sonic 1 as of the latest change in the code. The batch file `build.bat` is presumably the first port of call for _creating_ this output file. If that's not the case, check the Sonic Retro wiki and/or forum for information on how to build the disassembly (link in resources section below).

# Tasks

- [x] Set-up an emulator for running the build output.
- [x] Confirm `sonic1built.bin` is a runnable ROM binary by trying it in the emulator.
- [x] Remove the precompiled binary from the repository.
- [x] Confirm `build.bat` can be used to build the source and generate an output binary.
- [x] If these things aren't true then check for documentation on the Sonic Retro wiki.
- [x] Tidy-up any build scripts that are used.
- [x] Document the build process on the repo's readme.

# Resources

After some reading, it appears Kega Fusion is more accurate than Gens (and its derivatives) at emulating Mega Drive ROMs, so this should be the primary reference when testing the built results:
https://www.segaretro.org/Kega_Fusion

Article linked-to from the base repository:
http://info.sonicretro.org/disassemblies

# Branch

[`build`](https://github.com/Stack-in-a-box/sonic-the-hedgehog-speedrunners-edition/tree/build)
